export const GET_ALL_PRODUCTS_url = "http://localhost:3001/products/"
export const GET_PRODUCT_url = "http://localhost:3001/product/"
export const GET_PRODUCT_NAME_url = "http://localhost:3001/product/name/"
export const CREATE_PRODUCT_url = "http://localhost:3001/product/create"
export const UPDATE_PRODUCT_url = "http://localhost:3001/product/"// mas ${id}
export const DELETE_PRODUCT_url = "http://localhost:3001/product/delete/"
export const GET_CATEGORIAS_url = "http://localhost:3001/categories"
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_CART = "GET_CART";
export const REMOVE_FROM_CART= "REMOVE_FROM_CART";
